### ISSUE TITLE
About ‘DMP.DMP_STD’

### ISSUE THREAD

**Issue by Xmasterc** [Slifer64/SE3_DMP#1]
hey,I have been studying your article about DMP. I was lucky to find your program. When I tried to run, there were some problems. I would be grateful if you could answer them for me.
In dmp_pos_test.m file, what does DMP.DMP_STD this variable do？when i run it，matlab error reporting ‘Class DMP does not have the name 'DMP_STD’ Constant property or static method of STD '.So is ‘Az’ in the back.
I spent a lot of time and couldn't understand it, so I made a bad decision to ask you . If I disturb you, I'm very sorry. Finally, thank you for guiding me in the research of DMP

**Comment by Xmasterc** [comment]
I have solved the problem，thank you again！

**Comment by Slifer64** [comment]
Hi there!
This repository is deprecated. If you are interested in DMP I also have this updated repository:
https://github.com/Slifer64/new_gmp_structure.git
It provides both matlab and c++ interfaces. Also there are examples. The code is documented to great extent.
Hope this helps :)

**Comment by Xmasterc** [comment]
> 
it really helped me a lot！Thank you
